### PR TITLE
Improve usability in groups

### PR DESCRIPTION
**Pull request by kressh**
Hi!

This plugin is really awesome except it spams with help message in group chats. Because of autoreply to every unrecognized message. I don't think this behavior was any usefull anyway since it's not that hard to remember basic plugin commands.

So I suppressed /help messages, built `.hpi` package, all seems to work fine.

### CODE REVIEW

**Comment by nikitabelonogov** [comment]
Hi, @kressh 

I don't think that it is a good idea to just remove help message
Can you please more details about this issue?
Bot replays with help message on any message or only on the wrong command?

**Comment by kressh** [comment]
Yep. We have developers chat group in telegram with several bots (gitlab, trello, jenkins, hubot) and humans who chat in a same group.
I honestly think telegram bot shouldn't respond to unknown commands or messages because there can be other bots and people chatting. And also because telegram bots ecosystem forces us to use conventional `/start` command. I don't think there is any need for spam with help message to any unrecognized command, so it was since the times of IRC bots, everybody could remember `/help` command.

2018-03-23_712x775_scrot

**Comment by nikitabelonogov** [comment]
That a bad behavior

Actually, we have not face such a problem before, but let's remove help message for now.

offtopic: our Valera sends greetings
image

**Comment by kressh** [comment]
Haha, Valera greets y'all from gym!

valera-workout

Thanks guys!

**Pull request merged**
