### PR TITLE
Add chatId parameter to telegramSend() pipeline step

### PR DESCRIPTION
**Pull request by amezin**
Implements #8 and #27

### CODE REVIEW

**Comment by amezin** [comment]
And also #27

**Comment by devInteam** [comment]
Well it does not work. The 1.30 version has not the chatId property implemented.
jenkins reports:

00:00:05.647  WorkflowScript: 31: Invalid parameter "chatId", did you mean "message"? @ line 31, column 39.
00:00:05.647                            telegramSend ( chatId: -XXXXXXXXXXXXX,  message: "YYYYYYY")
00:00:05.647                                           ^
00:00:05.647

**Comment by romancin** [comment]
> Well it does not work. The 1.30 version has not the chatId property implemented.
> jenkins reports:
> 
> 00:00:05.647 WorkflowScript: 31: Invalid parameter "chatId", did you mean "message"? @ line 31, column 39.
> 00:00:05.647 telegramSend ( chatId: -XXXXXXXXXXXXX, message: "YYYYYYY")
> 00:00:05.647 ^
> 00:00:05.647

Same problem here.

**Comment by snk26** [comment]
Waiting for a solution to this problem

**Comment by romancin** [comment]
It is corrected on the latest commit, works for me 🙂

**Pull request merged**
